### YamlMime:Landing
title: Ansible en la documentación de Azure
summary: Aprenda a usar Ansible para automatizar el aprovisionamiento en la nube, la administración de configuración y las implementaciones de aplicaciones.
metadata:
  title: Ansible en la documentación de Azure
  description: Aprenda a usar Ansible para automatizar el aprovisionamiento en la nube, la administración de configuración y las implementaciones de aplicaciones.
  services: azure
  ms.service: ansible
  ms.topic: landing-page
  author: TomArcherMsft
  ms.author: tarcher
  ms.date: 09/11/2019
  ms.openlocfilehash: 8a33d1b9661ef84294a35c51ecd42a59dde68f23
  ms.sourcegitcommit: 8ef0a2ddaece5e7b2ac678a73b605b2073b76e88
  ms.translationtype: HT
  ms.contentlocale: es-ES
  ms.lasthandoff: 09/17/2019
  ms.locfileid: "71075062"
landingContent:
- title: Acerca de Ansible en Azure
  linkLists:
  - linkListType: overview
    links:
    - text: Acerca de Ansible en Azure
      url: ansible-overview.md
  - linkListType: architecture
    links:
    - text: Matriz de módulo y versión de Ansible
      url: ansible-matrix.md
- title: Instalación y configuración de Ansible
  linkLists:
  - linkListType: quickstart
    links:
    - text: Implementación de la plantilla de soluciones de Ansible en CentOS
      url: ansible-deploy-solution-template.md
    - text: Instalación de Ansible en máquinas virtuales Linux
      url: /azure/virtual-machines/linux/ansible-install-configure
    - text: Ejecución de cuadernos de estrategias en Cloud Shell
      url: ansible-run-playbook-in-cloudshell.md
  - linkListType: tutorial
    links:
    - text: Configuración de un inventario dinámico
      url: ansible-manage-azure-dynamic-inventories.md
  - linkListType: download
    links:
    - text: Extensión de Visual Studio Code para Ansible
      url: https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible
- title: Administración de Virtual Machines
  linkLists:
  - linkListType: quickstart
    links:
    - text: Configuración de máquinas virtuales Linux
      url: /azure/virtual-machines/linux/ansible-create-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
    - text: Administración de máquinas virtuales Linux
      url: /azure/virtual-machines/linux/ansible-manage-linux-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
- title: Administración de Virtual Machine Scale Sets
  linkLists:
  - linkListType: tutorial
    links:
    - text: Configuración de conjuntos de escalado de máquinas virtuales
      url: ansible-create-configure-vmss.md
    - text: Implementación de aplicaciones en conjuntos de escalado de máquinas virtuales
      url: ansible-deploy-app-vmss.md
    - text: Escalado automático de conjuntos de escalado de máquinas virtuales
      url: ansible-auto-scale-vmss.md
    - text: Actualización de una imagen personalizada
      url: ansible-vmss-update-image.md
- title: Administración de redes virtuales
  linkLists:
  - linkListType: tutorial
    links:
    - text: Configuración del emparejamiento
      url: ansible-vnet-peering-configure.md
    - text: Configuración de tablas de rutas
      url: ansible-create-configure-route-table.md
- title: Administración de AKS
  linkLists:
  - linkListType: tutorial
    links:
    - text: Configuración de clústeres de AKS
      url: ansible-create-configure-aks.md
    - text: Configuración de redes de Azure CNI
      url: ansible-aks-configure-cni-networking.md
    - text: Configuración de redes de Kubenet
      url: ansible-aks-configure-kubenet-networking.md
    - text: Configuración de los roles de control de acceso basado en rol en clústeres de AKS
      url: ansible-aks-configure-rbac.md
