- name: Ansible en la documentación de Azure
  href: ./index.yml
- name: Información general
  items:
    - name: Acerca de Ansible en Azure
      href: ./ansible-overview.md
- name: Guías de inicio rápido
  expanded: true
  items:
    - name: Implementación de la plantilla de soluciones de Ansible en CentOS
      href: ./ansible-deploy-solution-template.md
    - name: Instalación de Ansible en máquinas virtuales Linux
      href: ./ansible-install-configure.md
      maintainContext: true
    - name: Ejecución de cuadernos de estrategias en Cloud Shell
      href: ./ansible-run-playbook-in-cloudshell.md
    - name: Uso de Linux Virtual Machines
      expanded: true
      items:
        - name: Configuración de máquinas virtuales Linux
          href: ./ansible-create-vm.md
          maintainContext: true
        - name: Administración de máquinas virtuales Linux
          href: ./ansible-manage-linux-vm.md
          maintainContext: true
- name: Tutoriales
  items:
    - name: Azure Application Gateway
      items:
        - name: Administración del tráfico web
          href: ./ansible-create-configure-application-gateway.md
    - name: Azure App Service
      items:
        - name: Configuración de aplicaciones
          href: ./ansible-create-configure-azure-web-apps.md
        - name: Escalado de aplicaciones
          href: ./ansible-scale-azure-web-apps.md
    - name: Azure DevTest Labs
      items:
        - name: Configuración de laboratorios
          href: ./ansible-devtest-labs-configure.md
    - name: Azure Kubernetes Service (AKS)
      items:
        - name: Configuración de clústeres de AKS
          href: ./ansible-create-configure-aks.md
        - name: Configuración de redes de Azure CNI
          href: ./ansible-aks-configure-cni-networking.md
        - name: Configuración de redes de Kubenet
          href: ./ansible-aks-configure-kubenet-networking.md
        - name: Configuración de los roles de control de acceso basado en rol en clústeres de AKS
          href: ./ansible-aks-configure-rbac.md
    - name: HDInsight de Azure
      items:
        - name: Configuración de clústeres
          href: ./ansible-azure-hdinsight-configure.md
    - name: Azure Service Bus
      items:
        - name: Configuración de colas
          href: ./ansible-service-bus-queue-configure.md
        - name: Configuración de temas
          href: ./ansible-service-bus-topic-configure.md
    - name: Base de datos
      items:
        - name: Configuración de Azure Database for MySQL
          href: ./ansible-create-configure-mysql.md
        - name: Configuración de cuentas de Azure Cosmos DB.
          href: ./ansible-data-cosmos-configure.md
        - name: Configuración de Azure Cache for Redis
          href: ./ansible-data-cache-for-redis-configure.md
    - name: Inventario dinámico
      items:
        - name: Administración de recursos de Azure
          href: ./ansible-manage-azure-dynamic-inventories.md
    - name: Máquinas virtuales
      items:
        - name: Crear instancia de Shared Image Gallery
          href: ansible-vm-create-from-shared-generalized-image.md
    - name: Conjuntos de escalado de máquinas virtuales
      items:
        - name: Configuración
          href: ./ansible-create-configure-vmss.md
        - name: Implementación
          href: ./ansible-deploy-app-vmss.md
        - name: Escalado automático
          href: ./ansible-auto-scale-vmss.md
        - name: Actualización de una imagen personalizada
          href: ./ansible-vmss-update-image.md
        - name: Crear instancia de Shared Image Gallery
          href: ansible-vm-create-from-shared-generalized-image.md
    - name: Virtual network
      items:
        - name: Configuración del emparejamiento
          href: ./ansible-vnet-peering-configure.md
        - name: Configuración de tablas de rutas
          href: ./ansible-create-configure-route-table.md
- name: Ejemplos
  items:
    - name: Ansible Labs para Azure
      href: 'https://github.com/microsoft/ansiblelabs'
    - name: Ejemplos de cuadernos de estrategias de Azure con Ansible
      href: 'https://github.com/Azure-Samples/ansible-playbooks'
- name: Referencia
  items:
    - name: Roles de guión de procedimientos
      items:
        - name: azure_module
          href: 'https://galaxy.ansible.com/Azure/azure_modules/'
        - name: azure_preview_module
          href: 'https://galaxy.ansible.com/Azure/azure_preview_modules'
    - name: Versiones y características
      href: ./ansible-matrix.md
    - name: Todos los módulos de Azure
      href: 'https://docs.ansible.com/ansible/latest/modules/list_of_cloud_modules#azure'
- name: Recursos
  items:
    - name: Extensión de Visual Studio Code para Ansible
      href: 'https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible'