- name: Kubernetes en Azure
  href: ./index.yml
- name: Información general
- name: Guías de inicio rápido
  expanded: true
- name: Tutoriales
- name: Conceptos
- name: Guías paso a paso
  items:
    - name: Conservación de datos con Azure Files
      href: ../../aks/azure-files.md?toc=%2fazure%2fcontainer-service%2fkubernetes%2ftoc.json
    - name: Supervisión
    - name: Implementación de aplicaciones de Spring Boot
      items:
        - name: Implementación de una aplicación de Spring Boot en Linux en Azure Container Service
          href: container-service-deploy-spring-boot-app-on-linux.md
        - name: Implementación de una aplicación de Spring Boot en un clúster de Kubernetes en Azure Container Service
          href: container-service-deploy-spring-boot-app-on-kubernetes.md
        - name: Implementación de una aplicación de Spring Boot mediante el complemento de Maven fabric8
          href: container-service-deploy-spring-boot-app-using-fabric8-maven-plugin.md
- name: Referencia
  items:
    - name: Azure CLI
      href: /cli/azure/acs
    - name: PowerShell
      href: /powershell/module/az.compute
    - name: REST
      href: /rest/api/container-service
- name: Recursos
  items:
    - name: Azure Roadmap
      href: 'https://azure.microsoft.com/roadmap/'
    - name: 'Plantillas: ACS Engine'
      href: 'https://github.com/Azure/acs-engine'
    - name: Precios
      href: 'https://azure.microsoft.com/pricing/details/container-service/'
    - name: Disponibilidad en regiones
      href: 'https://azure.microsoft.com/regions/services/'
    - name: Stack Overflow
      href: 'https://stackoverflow.com/questions/tagged/azure-container-service'
    - name: Vídeos
      href: 'https://azure.microsoft.com/resources/videos/index/?services=container-service&sort=newest'