### YamlMime:Landing
title: Azure Arc Kubernetes (versión preliminar)
summary: Aprenda a administrar clústeres de Kubernetes con Azure Arc
metadata:
  title: Azure Arc Kubernetes
  description: Más información sobre cómo administrar máquinas locales en Azure
  author: 
  ms.service: azure-arc
  ms.topic: landing-page
  ms.date: 06/26/2020
  ms.author: 
  ms.openlocfilehash: 88d9ba51815496e7d8ec4ab3d22195c5b42c317b
  ms.sourcegitcommit: 86acfdc2020e44d121d498f0b1013c4c3903d3f3
  ms.translationtype: HT
  ms.contentlocale: es-ES
  ms.lasthandoff: 12/17/2020
  ms.locfileid: "97616973"
landingContent:
- title: Conexión de clústeres de Kubernetes con Azure mediante Azure Arc
  linkLists:
  - linkListType: overview
    links:
    - text: ¿Qué es Kubernetes habilitado para Azure Arc?
      url: overview.md
  - linkListType: quickstart
    links:
    - text: Jumpstart
      url: https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/
    - text: Conexión de un clúster
      url: connect-cluster.md
  - linkListType: how-to-guide
    links:
    - text: Implementación de configuraciones mediante GitOps
      url: use-gitops-connected-cluster.md
    - text: Implementación de gráficos de Helm mediante GitOps
      url: use-gitops-with-helm.md
    - text: Aplicación de GitOps mediante Azure Policy
      url: use-azure-policy.md
    - text: Implementación de cargas de trabajo de Azure IoT Edge
      url: deploy-azure-iot-edge-workloads.md
- title: Arquitectura de referencia
  linkLists:
  - linkListType: architecture
    links:
    - text: Administración de implementaciones y configuraciones para clústeres híbridos de Kubernetes
      url: /azure/architecture/hybrid/arc-hybrid-kubernetes
