### YamlMime:Landing
title: Azure Arc Kubernetes (versión preliminar)
summary: Aprenda a administrar clústeres de Kubernetes con Azure Arc
metadata:
  title: Azure Arc Kubernetes
  description: Más información sobre cómo administrar máquinas locales en Azure
  author: 
  ms.service: azure-arc
  ms.topic: landing-page
  ms.date: 06/26/2020
  ms.author: 
  ms.openlocfilehash: 9eeddfefe451eb524484df8a1986c7ec736c4c0f
  ms.sourcegitcommit: d79513b2589a62c52bddd9c7bd0b4d6498805dbe
  ms.translationtype: HT
  ms.contentlocale: es-ES
  ms.lasthandoff: 12/18/2020
  ms.locfileid: "97674379"
landingContent:
- title: Conexión de clústeres de Kubernetes con Azure mediante Azure Arc
  linkLists:
  - linkListType: overview
    links:
    - text: ¿Qué es Kubernetes habilitado para Azure Arc?
      url: overview.md
  - linkListType: quickstart
    links:
    - text: Conexión de un clúster
      url: connect-cluster.md
  - linkListType: how-to-guide
    links:
    - text: Implementación de configuraciones mediante GitOps
      url: use-gitops-connected-cluster.md
    - text: Implementación de gráficos de Helm mediante GitOps
      url: use-gitops-with-helm.md
    - text: Aplicación de GitOps mediante Azure Policy
      url: use-azure-policy.md
    - text: Implementación de cargas de trabajo de Azure IoT Edge
      url: deploy-azure-iot-edge-workloads.md
- title: Prueba de concepto
  linkLists:
  - linkListType: sample
    links:
    - text: Jumpstart
      url: https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/
- title: Arquitectura de referencia
  linkLists:
  - linkListType: architecture
    links:
    - text: Administración de implementaciones y configuraciones para clústeres híbridos de Kubernetes
      url: /azure/architecture/hybrid/arc-hybrid-kubernetes
